### ISSUE TITLE
Theme chakra UI

### ISSUE THREAD

**Issue by Avgilles** [bjcarlson42/nextjs-developer-portfolio#1]
Hello @bjcarlson42 , where i can defined the style theme of my projet ? I want to change for exemple the color of my dark theme in purple. The blue thème you add is the default value ? 
Thanks for your good tutorial

**Comment by bjcarlson42** [comment]
Sorry for the late response. The blue color is Chakra's default. I recommend changing the color of the background inside of `_app.js`.  You can use my personal website as an example because I didn't show this part in this tutorial series. https://github.com/bjcarlson42/benjamincarlson.io/blob/master/pages/_app.js#L28 Line 28 is where I am setting the background color. Any of the other styles you should use the `useColorModeValue` hook.
